on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout fonts
        uses: actions/checkout@v3
        with:
          repository: hhenrichsen/fonts
          token: ${{ secrets.FONTS_PAT }}
          path: fonts
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile

      - name: Build normal variant
        run: bun run deploy:normal
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          BUILD_VARIANT: normal

      - name: Build minimal variant
        run: bun run deploy:minimal
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          BUILD_VARIANT: minimal

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
